### ISSUE TITLE
doesn't know about recent rubies?

### ISSUE THREAD

**Issue by jrochkind** [postmodern/ruby-install#220]
Followed instructions in README to install ruby-install 0.5.0.  But it doesn't know about MRI 2.2?

~~~
$ ruby-install
Latest ruby versions:
Latest ruby versions:
  ruby:
    1.9.3-p547
    2.0.0-p576
    2.1.3
  jruby:
    1.7.16
  rbx:
    2.2.10
  maglev:
    1.0.0
  mruby:
    1.0.0
~~~

`ruby-install ruby` of course gets me 2.1.3 instead of actual latest 2.2.2. 

Where does ruby-install get it's list of rubies, does it need to be updated for more recent rubies?

**Comment by jrochkind** [comment]
Similarly, the README suggests `ruby-install ruby 2.2` to "Install a stable version of Ruby". I'm not sure if this is intended to install 2.2.0 or latest 2.2.x (2.2.2), and tried it to find out, but it does not seem to actually work:

~~~
...
Resolving cache.ruby-lang.org... 23.235.46.249, 199.27.76.249
Connecting to cache.ruby-lang.org|23.235.46.249|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-05-06 15:32:09 ERROR 404: Not Found.

!!! Download of http://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.tar.bz2 failed!
~~~

However, `ruby-install ruby 2.2.2` does, even though 2.2.2 wasn't listed in `ruby-install`. It would be nice not to have to keep track of what the latest MRI version is though, and have ruby-install either tell me, or accept an instruction "just give me the latest 2.2.x".

**Comment by havenwood** [comment]
The plan is to automatically download any outdated version and checksum files from [ruby-versions](https://github.com/postmodern/ruby-versions) when appropriate ruby-install commands are run. See #175. I look forward to that feature!

At the moment ruby-install 0.5.0 ships with somewhat dated version and checksum files. Until the `--update/--no-update` feature ships, while installing you can run `make update` to download the latest version and checksum files before `sudo make install`. Or installing from latest master instead of 0.5.0 will provide updated versions and checksums.

**Comment by jrochkind** [comment]
Cool. Should `make update` be added to install instructions in the README? 

Also the README suggests "Does not require updating every time a new Ruby version comes out.", which I guess is technically true, you can install whatever ruby version you want, you just have to know about it, it won't be listed in the available versions. I think maybe the README should explain?

**Comment by postmodern** [comment]
Once we have decent test coverage on the [cache](https://github.com/postmodern/ruby-install/tree/cache) branch, updates will happen automatically.
