### ISSUE TITLE
Make the installed ruby default

### ISSUE THREAD

**Issue by KINGSABRI** [postmodern/ruby-install#249]
Hey! 
Thanks man for the script, it saves our day.

Now, We need some option to make the new installed version as the default Ruby version of our system. Would you make this easier, please? 

I'm using Kubuntu 15.10

**Comment by havenwood** [comment]
Installing system-wide would make the installed Ruby your default (as long as `/usr/local/bin` is in the front of your `PATH`): `sudo ruby-install --system ruby`

**Comment by KINGSABRI** [comment]
Thanks, actually the default path is ubuntu is 

```bash
$whereis ruby
ruby: /usr/bin/ruby2.1 /usr/bin/ruby2.2 /usr/bin/ruby /usr/lib/ruby /usr/local/bin/ruby /usr/local/lib/ruby /usr/share/man/man1/ruby.1.gz
```

**Comment by havenwood** [comment]
That's not related to your `PATH`. I'd expect you'll see the same if you try `PATH="" /usr/bin/whereis ruby` since `whereis` looks for source, binaries, and manpages in standard locations not just in your `PATH`. If you'd like to see the order or Rubies in your `PATH` try `which -a` instead of `whereis`.

The standard `PATH` in Ubuntu will vary by type of install but here's an example: 
```sh
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```

**Comment by KINGSABRI** [comment]
Aha, that's right 
```bash
 $which -a ruby
/usr/local/bin/ruby
/usr/bin/ruby
```

maybe I've to make symlink for it in `/usr/bin/ruby`

**Comment by postmodern** [comment]
@KINGSABRI check your `$PATH` and make sure `/usr/local/bin` is before `/usr/bin`, that way your installed ruby overrides the system's ruby.

**Comment by havenwood** [comment]
Closing this since the issue was resolved.
