### ISSUE TITLE
Ubuntu 16.04 and rubinius fails to install, missing apt dependency

### ISSUE THREAD

**Issue by adam-stokes** [postmodern/ruby-install#279]
Running Ubuntu 16.04 (Xenial) there is no longer a ruby1.9.1-dev packaged in the archive, see this error:

```
[adam:~] 54s $ ruby-install rbx 3.43
>>> Installing rbx 3.43 into /home/adam/.rubies/rbx-3.43 ...
>>> Installing dependencies for rbx 3.43 ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package ruby1.9.1-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ruby1.9.1-dev' has no installation candidate
```

The available ruby interpreter now is `ruby 2.3.0` which you can get by installing `ruby` package.

In order to support prior versions of Ubuntu we'd need to probably check `/etc/lsb-release` and add the package dependency accordingly.

**Comment by rickhull** [comment]
I ran into this problem and more, trying to `ruby-install rbx` on Ubuntu 19.10.  It appears that rubinius has updated their build system (per https://github.com/postmodern/ruby-install/issues/342#issuecomment-481897733) and there is significant breakage, at least on Debian-based systems.

I located dependencies.txt and played around a little.  `ruby-dev` rather than `ruby-1.9-dev` is needed.  Both this and the specified LLVM package do not exist on modern Debians.  There are newer LLVMs, but I couldn't make them work.  The failure is at gettid.  I'll update this later with actual details and logs.

**Comment by rickhull** [comment]
With `ruby-dev` and `llvm-dev` and `clang`, I get rbx successfully installed:

```
Successfully installed Rubinius 4.15

Add '/home/rwh/.rubies/rbx-4.15/bin' to your PATH. Available commands are:

  rbx, ruby, rake, gem, irb, rdoc, ri

  1. Run Ruby files with 'rbx path/to/file.rb'
  2. Start IRB by running 'rbx' with no arguments

>>> Successfully installed rbx 4.15 into /home/rwh/.rubies/rbx-4.15
```
