### ISSUE TITLE
core dump with ruby 2.3.8 and ubuntu 18.04

### ISSUE THREAD

**Issue by mustmodify** [postmodern/ruby-install#365]
I used ruby-install to install ruby-2.3.8. I consistently get a core dump when trying to migrate a Rails app. I'm not sure who I should ask to help with this issue -- if you could point me in the correct direction, that would be appreciated.

https://gist.github.com/mustmodify/a29a27d7a493323326b960873011d399

* I installed the OS within the last month so the environment is, hopefully, somewhat lacking in "surprises.") Or maybe that means there are more, not clear.

* Based on a StackOverflow post, I compiled what I believe is the correct version of OpenSSL. I used the following to install this ruby -- `ruby-install ruby-2.3.8 -- --with-openssl-dir=/opt/openssl-1.0.2s/`

* To ensure availability to all users, I installed ruby as `root`.

**Comment by mustmodify** [comment]
This post seems to (further) confirm my suspicion that way I originally installed was incorrect. 

https://stackoverflow.com/questions/44116005/openssl-error-installing-ruby-2-1-x-and-2-3-x-on-archlinux-with-ruby-install-rub

which is fine. So here are my thoughts.

1. Can ruby 2.3.8 be installed on ubuntu 18.04?
2. If so, do I need to provide some kind of access to an old version of OpenSSL, presumably 1.0.something. I have 1.0.2s installed at /opt/openssl-1.0.2s.
3. Does the entire system need to be using it, or is it sufficient to just compile OpenSSL and point Ruby to it? I ask because different version of Ruby will, I suppose, need different versions of OpenSSL.
4. When I specify --with-openssl-dir, what actually needs to be in that directory?

**Comment by postmodern** [comment]
A little late replying to this, but [Ruby 2.3 has reached End-of-Life](https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/) in March. If you want to test if it's a ruby-install issue, you could try manually compiling the ruby using these copy-and-paste [instructions](https://github.com/postmodern/chruby/wiki/Ruby). You could pass in `--with-openssl-dir` pointing to the alternate directory which the openssl was installed into. When dealing with SegFaults, try running `ruby` inside `gdb` to accurate get a full stack trace. Since it's SegFaulting at 0x0, that looks like an NULL function pointer deref.

It's usually less work to just port the app to a recent/supported version of Ruby, than deal with older/buggier versions of openssl.
