### ISSUE TITLE
ruby-3.0.0-preview2 can’t be downloaded because it has no .tar.bz2

### ISSUE THREAD

**Issue by tomstuart** [postmodern/ruby-install#385]
3.0.0-preview2 was [just released](https://www.ruby-lang.org/en/news/2020/12/08/ruby-3-0-0-preview2-released/) but they haven’t published a `.tar.bz2` download. If this is intentional then the [`use_tar_xz_for_ruby`](https://github.com/postmodern/ruby-install/compare/master...use_tar_xz_for_ruby) changes might need to be prioritised.

**Comment by postmodern** [comment]
It's finally happening.

**Comment by postmodern** [comment]
Merged into master. Will release 0.8.0 shortly.

**Comment by tomstuart** [comment]
Thank you!

**Comment by todd-a-jacobs** [comment]
Per the [Ruby downloads](https://www.ruby-lang.org/en/downloads/) page:

```
Ruby 3.0.0-preview2
sha256: 9de8661565c2b1007d91a580e9a7e02d23f1e8fc8df371feb15a2727aa05fd9a
```

I mention it so that the SHA-256 can be included if/when the ruby-install definitions are updated, not just the installer logic. Right now, it fails with:

$ ruby-install ruby 3.0.0-preview-2 --sha256 9de8661565c2b1007d91a580e9a7e02d23f1e8fc8df371feb15a2727aa05fd9a
!!! Download of https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.0-preview-2.tar.bz2 failed!

as expected, but the archive's hash should be updated as well.

**Comment by postmodern** [comment]
@todd-a-jacobs that appears to be the sha256 of the `.tar.gz` file, not the `.tar.xz` (will be the new default). The sha256 in ruby-versions matches the ruby-lang.org news post.

* https://github.com/postmodern/ruby-versions/blob/1c1d70157a92f29611d01d26f305ce3f226ecd8c/ruby/checksums.sha256#L582
* https://www.ruby-lang.org/en/news/2020/12/08/ruby-3-0-0-preview2-released/

**Comment by postmodern** [comment]
0.8.0 has been released.
