### ISSUE TITLE
What about changing `src_dir` to `~/.local/ruby-install/`?

### ISSUE THREAD

**Issue by ioquatix** [postmodern/ruby-install#437]
https://github.com/postmodern/ruby-install/blob/7abd329bff29f2bf5a4fa5563bd61b8976bb1cac/share/ruby-install/ruby-install.sh#L20

It's a recommended place for local application files.

**Comment by postmodern** [comment]
In the 1.0.0 branch I started changing the directory constants to use XDG directories:
* https://github.com/postmodern/ruby-install/commit/eadb47c04c68559ffaf39e7a162412282c6459c9
* https://github.com/postmodern/ruby-install/commit/46706247d540d04b87abc273508ebb2937383696

However, I am slightly nervous about switching to XDG directories because macOS users tend not to use XDG, as it's more of a Linux/freedesktop.org standard.

**Comment by ioquatix** [comment]
This looks great to me.

In my experience, it's acceptable behaviour for macOS, even if the system itself doesn't respect those directories.

**Comment by ioquatix** [comment]
Looking forward to a 1.0 release :)
