### ISSUE TITLE
`--with-opt-dir` doesn't prevent Ruby from seeing OpenSSL 3 headers/lib

### ISSUE THREAD

**Issue by dgholz** [postmodern/ruby-install#458]
## Description

This _does_ also happen when compiling Ruby manually, but I see in the [Ruby MacOS CI steps](https://github.com/ruby/ruby/blob/833b32f503abb9712dbb3a6825b1730c8ee1e912/.github/workflows/macos.yml#L67) that they use `--with-openssl-dir` instead.

Recently, [Homebrew updated loads of formulæ to use OpenSSL 3](https://github.com/Homebrew/homebrew-core/issues/134251), and I see the latest version of their OpenSSL package (`3.1.1_1`) get installed when I updated some frequently-used tools (like `curl`) . When I tried compiling Ruby afterwards, I was surprised to see some OpenSSL 3 errors appear in the output.

I traced it to how Ruby figures out where to find OpenSSL, and how the paths in the `--with-opt-dir` don't preclude it from making its own search. It then configures `~/src/ruby-3.1.4/ext/openssl/Makefile` like:
```
[...]
INCFLAGS = -I. -I$(arch_hdrdir) -I$(hdrdir) -I$(srcdir) -I/opt/homebrew/Cellar/openssl@3/3.1.1_1/include
DEFS     =
CPPFLAGS = -DRUBY_EXTCONF_H=\"$(RUBY_EXTCONF_H)\" -I/opt/homebrew/opt/openssl@1.1/include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/libyaml/include -I/opt/homebrew/opt/gdbm/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT $(DEFS) $(cppflags)
CXXFLAGS = $(CCDLFLAGS) -fdeclspec  $(ARCH_FLAG)
ldflags  = -L. -fstack-protector-strong -L/opt/homebrew/opt/openssl@1.1/lib -L/opt/homebrew/opt/readline/lib -L/opt/homebrew/opt/libyaml/lib -L/opt/homebrew/opt/gdbm/lib -L/opt/homebrew/Cellar/openssl@3/3.1.1_1/lib
[...]
```

I noticed that specifying the path to OpenSSL explicitly let it work just fine:
```
$ ruby-install 3.1.4 -- --with-openssl-dir="$(brew --prefix openssl@1.1)"
[...]
>>> Successfully installed ruby 3.1.4 into /Users/danielholz/.rubies/ruby-3.1.4
```

## Steps To Reproduce

Steps to reproduce the bug:
1. `brew update && brew upgrade`
   * or `brew install openssl`
   * or `brew upgrade openssl`
3. `ruby-install 3.1.4`

## Expected Behavior

No weird mentions of OpenSSL 3 in compilation errors.

## Actual Behavior

```
ossl_ts.c:829:5: error: incomplete definition of type 'struct TS_verify_ctx'
    TS_VERIFY_CTX_set_certs(ctx, x509inter);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./openssl_missing.h:215:46: note: expanded from macro 'TS_VERIFY_CTX_set_certs'
#  define TS_VERIFY_CTX_set_certs(ctx, crts) TS_VERIFY_CTS_set_certs(ctx, crts)
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./openssl_missing.h:195:52: note: expanded from macro 'TS_VERIFY_CTS_set_certs'
#  define TS_VERIFY_CTS_set_certs(ctx, crts) ((ctx)->certs=(crts))
                                              ~~~~~^
/opt/homebrew/Cellar/openssl@3/3.1.1_1/include/openssl/ts.h:407:16: note: forward declaration of 'struct TS_verify_ctx'
typedef struct TS_verify_ctx TS_VERIFY_CTX;
               ^
1 warning and 1 error generated.
make[2]: *** [ossl_ts.o] Error 1
make[1]: *** [ext/openssl/all] Error 2
make: *** [build-ext] Error 2
!!! Compiling ruby 3.1.4 failed!
ERROR: Unable to install ruby version: 3.1.4
```

## Environment

    $ ruby-install --version
    ruby-install: 0.9.0 # which matches https://github.com/postmodern/ruby-install/blob/v0.9.1/share/ruby-install/ruby-install.sh#L5

    $ uname -a
    Darwin daniel-holz-laptop 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64`

    $ cc --version
    Apple clang version 14.0.3 (clang-1403.0.22.14.1)
    Target: arm64-apple-darwin22.5.0
    Thread model: posix
    InstalledDir: /Library/Developer/CommandLineTools/usr/bin
  
    $ openssl version
    OpenSSL 3.1.1 30 May 2023 (Library: OpenSSL 3.1.1 30 May 2023)

**Comment by dgholz** [comment]
I also noticed that unpinning OpenSSL in the `ruby` dependencies let Ruby compile just fine against OpenSSL `3.1.1`.

**Comment by dgholz** [comment]
Ah, this seems extremely similar to https://github.com/postmodern/ruby-install/issues/412#issuecomment-1118178152

**Comment by todd-a-jacobs** [comment]
I've been running into this, too. As a work-around, if you are using Homebrew on an M1/M2 with an _/opt_ directory rather than installed into _/usr/local_, the following works for me:

```bash
LDFLAGS="-L/opt/homebrew/opt/openssl@1.1/lib" \
    CPPFLAGS="-I/opt/homebrew/opt/openssl@1.1/include" \
    PKG_CONFIG_PATH="/opt/homebrew/opt/openssl@1.1/lib/pkgconfig" \
    PATH="/opt/homebrew/opt/openssl@1.1/bin:$PATH" \
    ruby-install -c ruby 3.2.1 -- --enable-yjit
```

Note that this may be necessary regardless of the Ruby version you're installing if you need OpenSSL 1.1 and have both openssl@1 and openssl@3 installed. If your Homebrew is putting things under _/usr/loca_l, you can adjust the paths above accordingly. Call `brew info openssl@1.1` to find the right values for your system.

Until/unless Ruby can compile against OpenSSL 3, or against  the native or Homebrew versions of LibreSSL, this likely will be an ongoing pain point for some people. This includes those who may need rustc and/or a patched OpenSSL to build TruffleRuby-GraalVM from source instead of using Homebrew's GraalVM cask, which is another time-saver I highly recommend for those with SSL or Java build problems.

Hope this helps!

**Comment by todd-a-jacobs** [comment]
> I also noticed that unpinning OpenSSL in the `ruby` dependencies let Ruby compile just fine against OpenSSL `3.1.1`.

I think compiling against the latest _stable_ OpenSSL or LibreSSL (whether statically or dynamically) is better for security than compiling against specific versions, since that allows for people to keep their systems patched. To be honest, though, I'm not sure whether the way Homebrew installs OpenSSL allows for the latest version on the system to be used, or if it compiles in the OpenSSL version that was present when Ruby was built by ruby-install. That's kind of an important question in my mind, and I don't currently know how that works with ruby-install.

**Comment by dgholz** [comment]
Thanks for the tips, I'll try them out.

> To be honest, though, I'm not sure whether the way Homebrew installs OpenSSL allows for the latest version on the system to be used, or if it compiles in the OpenSSL version that was present when Ruby was built by ruby-install. That's kind of an important question in my mind, and I don't currently know how that works with ruby-install.

Ruby itself doesn't directly link to OpenSSL. It gets linked to via the `openssl` gem, which is a Ruby extension. By default, that extension links to whatever OpenSSL library you have installed when the gem was built. I can see it when I inspect the `openssl.bundle` with `otool`:

```
$ otool -L ~/.gem/ruby/3.1.4/gems/openssl-3.1.0/ext/openssl/openssl.bundle 
/Users/danielholz/.gem/ruby/3.1.4/gems/openssl-3.1.0/ext/openssl/openssl.bundle:
	/opt/homebrew/opt/openssl@1.1/lib/libssl.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/opt/homebrew/opt/openssl@1.1/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.100.3)
```

If I update `openssl@1.1` & Homebrew puts newer files in those locations, the `openssl` gem will load them when it's `require`d. So it automatically uses updates. The gem won't switch from `1.1` to `3` without being recompiled, since the shared libraries will have different paths.

**Comment by chadhs** [comment]
Has anyone figured out a fix for this yet?  Was just trying to install ruby with `ruby-install` on a new Mac and I'm getting the same compile error.

**Comment by skaes** [comment]
--with-opt-dir=<openssl-dir> is the wrong approach to select the openssl version. The openssl gem looks for pkg-config information first and ignores that only when --with-openssl-dir=... is specified. I know, because I contributed the patch: https://github.com/ruby/openssl/commit/b23fa75aa3a514e83e40d5220339f992f947befd.

Note that the option only works for ruby versions 3.1.1 and higher. Anything smaller can not be compiled without applying the patch first.

**Comment by skaes** [comment]
Version 3.1.1 and higher can be installed with a single command:

```
ruby-install ruby 3.2.2 --with-openssl-dir=/opt/homebrew/opt/openssl@1.1
 ```

**Comment by semaperepelitsa** [comment]
```
> ruby-install ruby 3.2.2 --with-openssl-dir=/opt/homebrew/opt/openssl@1.1
ruby-install: unrecognized option --with-openssl-dir=/opt/homebrew/opt/openssl@1.1
```

Should be:

```
ruby-install ruby 3.2.2 -- --with-openssl-dir=/opt/homebrew/opt/openssl@1.1
```

**Comment by chadhs** [comment]
thank you everyone!
what about for versions 2.7.6 and under?
